import Link from 'next/link';
export default function ConnectionGuide() {
  return <main className="min-h-dvh bg-[#080c14] px-4 py-8 text-gray-200"><article className="mx-auto max-w-3xl space-y-8">
    <header className="space-y-3"><Link href="/" className="text-cyan-300 underline">Volver a Jetree</Link><h1 className="text-2xl font-bold">Tus cuentas de Claude y Google en Jetree</h1><p>Cada usuario conecta su propia cuenta. Las API keys son una alternativa opcional, con cuota y facturación separadas.</p></header>
    <section id="claude" className="space-y-4 rounded-xl border border-purple-800 p-5"><h2 className="text-xl font-semibold">Claude: conversar desde su aplicación oficial</h2>
      <p>Tu plan de Claude se usa en Claude. Jetree se conecta como una herramienta MCP para consultar GitHub y Drive y proponer cambios. Este flujo no ejecuta modelos de Jetree ni consume una API de Anthropic. Para usar Claude dentro del chat de Jetree, conectá una API key.</p>
      <ol className="list-inside list-decimal space-y-3"><li>Iniciá sesión en Jetree y conectá tus herramientas de GitHub o Drive. Habilitalas en los agentes que quieras usar.</li><li>En Conexiones de modelos → Claude, copiá la dirección del conector. Usá el dominio público HTTPS del entorno que querés conectar, nunca una dirección de túnel o localhost.</li><li>En Claude abrí Personalizar → Conectores → Agregar conector personalizado. Nombre: Jetree. Pegá la dirección y continuá.</li><li>Elegí iniciar sesión y Registrar automáticamente como cliente OAuth. Si necesitás un ID manual: <code>jetree-claude</code>; no requiere secreto. En Team o Enterprise, el propietario primero debe agregar el conector; luego cada miembro autoriza su cuenta individual.</li><li>En la pantalla de Jetree, iniciá sesión y seleccioná los agentes permitidos. Por defecto el acceso es de lectura. Marcá propuestas de cambios solo si las necesitás.</li><li>Activá Jetree en tu chat de Claude desde + → Conectores. Probá: «Listá mis agentes de Jetree y consultá los últimos commits de la rama dev del repositorio que te indique».</li><li>Para crear un archivo, rama o PR, Claude devuelve una propuesta pendiente. Abrí el enlace de aprobaciones, revisá su contenido y aprobá o rechazá desde Jetree. Claude no puede aprobarla. Volvé a Claude y pedile consultar el estado de la propuesta.</li></ol>
      <p>Las ramas nuevas llevan el prefijo <code>jetree-branch-</code>. Los PR se crean como borrador; no se mergean automáticamente.</p>
      <p>El acceso vence en 7 días. Podés revocarlo antes desde Conexiones de modelos → Claude. Quitar el conector en Claude y revocar en Jetree evita dejar accesos activos. Las propuestas pendientes no se ejecutan por revocar o reconectar.</p>
      <p>Claude recibe los resultados de las consultas que le pedís; elegí qué datos compartís. No recibe tus claves de proveedores, contraseña ni el historial de conversaciones de Jetree.</p>
      <details><summary className="cursor-pointer text-cyan-300">Si no conecta o una herramienta falla</summary><ul className="mt-3 list-inside list-disc space-y-2"><li>401: conectá o reconectá y autorizá tu cuenta de Jetree.</li><li>Sin agentes: seleccioná un agente activo durante la autorización; si cambiaste permisos, reconectá.</li><li>Herramienta no autorizada: habilitá GitHub o Drive en ese agente.</li><li>Conexión requerida: conectá tu propia cuenta de GitHub o Drive en Jetree. Autorizar MCP no conecta automáticamente esos proveedores.</li><li>Solo lectura: reconectá solicitando el permiso de propuestas. Nunca se ejecuta una escritura desde la herramienta de lectura.</li><li>Servidor inaccesible: Claude conecta desde sus servidores. Usá un dominio público con HTTPS válido.</li></ul></details>
      <a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp" target="_blank" rel="noreferrer" className="block text-cyan-300 underline">Ayuda oficial de Claude</a>
    </section>
    <section id="google" className="space-y-4 rounded-xl border border-cyan-800 p-5"><h2 className="text-xl font-semibold">Google: conexión personal con Antigravity</h2>
      <p className="text-amber-200">La conexión personal está en actualización. Todavía no está habilitada para conversaciones de Jetree. Gemini por API sigue disponible cuando lo elegís explícitamente.</p>
      <p>Google dejó de atender cuentas personales gratuitas, Pro y Ultra mediante Gemini CLI el 18 de junio de 2026 y las trasladó a Antigravity CLI. Repetir el login del conector anterior no resuelve ese rechazo.</p>
      <p>Estamos verificando el conector nuevo con Antigravity oficial en Windows. Cada usuario inicia sesión con su propia cuenta en el navegador de Google. Las credenciales quedan bajo el control de Antigravity y del almacén seguro del sistema; Jetree no solicita ni recibe el token de Google.</p>
      <details><summary className="cursor-pointer text-cyan-300">Probar el login del conector en desarrollo</summary><ol className="mt-3 list-inside list-decimal space-y-2"><li>Instalá Node.js 22 o superior desde su sitio oficial.</li><li><a href="/downloads/jetree-google-connector.tar.gz" download className="text-cyan-300 underline">Descargá la versión de prueba</a> y extraela en una carpeta nueva.</li><li>En una terminal propia ejecutá <code>npm ci</code> y luego <code>npm run login</code>. Descarga Antigravity oficial y verifica su SHA-512; no instala extensiones ni modifica el PATH.</li><li>Completá vos el login y los consentimientos oficiales. Revisá la cuenta elegida; no compartas códigos ni tokens. No importes configuraciones, plugins o herramientas de otra instalación.</li><li>Al llegar al chat de Antigravity, salí con <code>/quit</code>. Vincular y enviar mensajes permanecen bloqueados hasta terminar las pruebas de aislamiento y respuesta real.</li></ol></details>
      <p>El conector es individual y requiere el equipo encendido. Telegram y las ejecuciones de servidor continúan usando las conexiones API configuradas.</p>
      <a href="https://developers.googleblog.com/an-important-update-transitioning-gemini-cli-to-antigravity-cli/" target="_blank" rel="noreferrer" className="block text-cyan-300 underline">Anuncio oficial de Google</a>
      <a href="https://antigravity.google/docs/cli/install/" target="_blank" rel="noreferrer" className="block text-cyan-300 underline">Autenticación oficial de Antigravity</a>
    </section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">OpenAI</h2><p>La conexión de ChatGPT por suscripción está pendiente de acceso autorizado por OpenAI. Mientras tanto, podés usar una API key de OpenAI Platform con su cuota y facturación propias.</p></section>
  </article></main>;
}
