import Link from 'next/link';
export default function ConnectionGuide() {
  return <main className="min-h-dvh bg-[#080c14] px-4 py-8 text-gray-200"><article className="mx-auto max-w-3xl space-y-8">
    <header className="space-y-3"><Link href="/" className="text-cyan-300 underline">Volver a Jetree</Link><h1 className="text-2xl font-bold">Tus cuentas de Claude y Google en Jetree</h1><p>Cada usuario conecta su propia cuenta. Las API keys son una alternativa opcional, con cuota y facturación separadas.</p></header>
    <section id="claude" className="space-y-4 rounded-xl border border-purple-800 p-5"><h2 className="text-xl font-semibold">Claude: conversar desde su aplicación oficial</h2>
      <p>Tu plan de Claude se usa en Claude. Jetree se conecta como una herramienta MCP para consultar GitHub y Drive y proponer cambios. Este flujo no ejecuta modelos de Jetree ni consume una API de Anthropic. Para usar Claude dentro del chat de Jetree, conectá una API key.</p>
      <ol className="list-inside list-decimal space-y-3"><li>Iniciá sesión en Jetree y conectá tus herramientas de GitHub o Drive. Habilitalas en los agentes que quieras usar.</li><li>En Conexiones de modelos → Claude, copiá la dirección del conector. Usá el dominio público HTTPS del entorno que querés conectar, nunca una dirección de túnel o localhost.</li><li>En Claude abrí Personalizar → Conectores → Agregar conector personalizado. Nombre: Jetree. Pegá la dirección y continuá.</li><li>Elegí iniciar sesión y Registrar automáticamente como cliente OAuth. Si necesitás un ID manual: <code>jetree-claude</code>; no requiere secreto. En Team o Enterprise, el propietario primero debe agregar el conector; luego cada miembro autoriza su cuenta individual.</li><li>En la pantalla de Jetree, iniciá sesión y seleccioná los agentes permitidos. Por defecto el acceso es de lectura. Marcá propuestas de cambios solo si las necesitás.</li><li>Activá Jetree en tu chat de Claude desde + → Conectores. Probá: «Listá mis agentes de Jetree y consultá los últimos commits de la rama dev del repositorio que te indique».</li><li>Para crear un archivo, rama o PR, Claude devuelve una propuesta pendiente. Abrí el enlace de aprobaciones, revisá su contenido y aprobá o rechazá desde Jetree. Claude no puede aprobarla. Volvé a Claude y pedile consultar el estado de la propuesta.</li></ol>
      <p>Las ramas nuevas llevan el prefijo <code>jetree-branch-</code>. Los PR se crean como borrador; no se mergean automáticamente.</p>
      <p>El acceso vence en 7 días. Podés revocarlo antes desde Conexiones de modelos → Claude. Quitar el conector en Claude y revocar en Jetree evita dejar accesos activos. Las propuestas pendientes no se ejecutan por revocar o reconectar.</p>
      <p>Claude recibe los resultados de las consultas que le pedís; elegí qué datos compartís. No recibe tus claves de proveedores, contraseña ni el historial de conversaciones de Jetree.</p>
      <details><summary className="cursor-pointer text-cyan-300">Si no conecta o una herramienta falla</summary><ul className="mt-3 list-inside list-disc space-y-2"><li>401: conectá o reconectá y autorizá tu cuenta de Jetree.</li><li>Sin agentes: seleccioná un agente activo durante la autorización; si cambiaste permisos, reconectá.</li><li>Herramienta no autorizada: habilitá GitHub o Drive en ese agente.</li><li>Conexión requerida: conectá tu propia cuenta de GitHub o Drive en Jetree. Autorizar MCP no conecta automáticamente esos proveedores.</li><li>Solo lectura: reconectá solicitando el permiso de propuestas. Nunca se ejecuta una escritura desde la herramienta de lectura.</li><li>Servidor inaccesible: Claude conecta desde sus servidores. Usá un dominio público con HTTPS válido.</li></ul></details>
      <a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp" target="_blank" rel="noreferrer" className="block text-cyan-300 underline">Ayuda oficial de Claude</a>
    </section>
    <section id="google" className="space-y-4 rounded-xl border border-cyan-800 p-5"><h2 className="text-xl font-semibold">Google: chat de Jetree con tu equipo conectado</h2>
      <p>El conector usa el inicio de sesión oficial de Gemini CLI en tu computadora. La cuota y los modelos disponibles dependen de tu cuenta y de Google; no equivale al catálogo de Gemini API. Jetree utiliza la selección automática de Gemini CLI. El equipo debe estar encendido y conectado.</p>
      <ol className="list-inside list-decimal space-y-3"><li>Instalá Node.js 22 o superior desde <a href="https://nodejs.org/" target="_blank" rel="noreferrer" className="text-cyan-300 underline">su sitio oficial</a>.</li><li><a href="/downloads/jetree-google-connector.tar.gz" download className="text-cyan-300 underline">Descargá el conector personal de Jetree</a> y extraelo en una carpeta nueva. No necesitás acceso al repositorio ni ser administrador de Jetree.</li><li>Abrí una terminal en esa carpeta y ejecutá <code>npm ci</code>. Luego <code>npm run login</code>. Elegí el inicio de sesión con Google en su navegador oficial. No pegues una API key. Al terminar, salí del CLI con <code>/quit</code>.</li><li>En Jetree → Conexiones de modelos → Google, presioná Vincular mi equipo. El código dura 5 minutos y es de un solo uso; no lo compartas.</li><li>En la terminal ejecutá <code>npm run pair</code>. Indicá el dominio público de Jetree, el código y un nombre para tu equipo. Elegí dev para pruebas o producción para uso real; se vinculan por separado.</li><li>Ejecutá <code>npm start</code> y mantené la terminal abierta. En Jetree actualizá el estado hasta ver Conectado.</li><li>Abrí un agente de Google y elegí tu equipo en Conexión para esta conversación. Mandá un mensaje de prueba. Si el equipo se desconecta, Jetree informa el error y no cambia automáticamente a API.</li></ol>
      <p>Si el CLI pregunta si confiás en la carpeta, elegí «Don&apos;t trust». No necesita confiar en la carpeta padre. Si se reinicia para aplicar esa elección y muestra «Login no completado», repetí <code>npm run login</code> y completá el acceso Google.</p>
      <p>Las herramientas se ejecutan en Jetree con los permisos y aprobaciones habituales. El CLI local no tiene herramientas de archivos, terminal, extensiones ni otros MCP habilitados. Solo procesa el texto que le envía la conversación.</p>
      <p>Este conector sirve para el chat web. Los bots de Telegram y las ejecuciones de servidor continúan usando las conexiones API configuradas; no dependen de tu computadora. Para detenerlo usá Ctrl+C. Revocá el equipo desde Jetree cuando ya no lo uses.</p>
      <details><summary className="cursor-pointer text-cyan-300">Si Google no responde</summary><ul className="mt-3 list-inside list-disc space-y-2"><li>Equipo desconectado: comprobá que <code>npm start</code> siga abierto y que vinculaste el entorno correcto.</li><li>Código vencido: generá uno nuevo y repetí <code>npm run pair</code>.</li><li>Error de acceso o cuota: repetí <code>npm run login</code> y comprobá las condiciones de tu cuenta de Google.</li><li>La respuesta tarda demasiado: probá una consulta más corta. Jetree cancela el trabajo vencido; no utiliza una API de respaldo.</li></ul></details>
    </section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">OpenAI</h2><p>La conexión de ChatGPT por suscripción está pendiente de acceso autorizado por OpenAI. Mientras tanto, podés usar una API key de OpenAI Platform con su cuota y facturación propias.</p></section>
  </article></main>;
}
