name: Deploy dev
on:
  push:
    branches: [dev]
permissions:
  contents: read
concurrency:
  group: deploy-dev
  cancel-in-progress: false
jobs:
  application:
    uses: ./.github/workflows/verify.yml
  container:
    uses: ./.github/workflows/container.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  deploy:
    needs: [application, container, e2e]
    if: vars.AUTODEPLOY_DEV == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
